name: test
on:
  push:
    branches:
    - 'main'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: npm ci
        run: |
          npm ci --ignore-scripts

      - name: npm test
        run: |
          npm test
